### ISSUE TITLE
Unable to get coordinates from https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations

### ISSUE THREAD

**Issue by r-jean-pierre** [julcollas/hass-vigicrues#10]
Hello!

L'url est down, ca semble faire une erreur à l'intégration, précisément ici:
Source: custom_components/vigicrues/sensor.py:154

Bien sur le problème est du coté hubeau

**Comment by julcollas** [comment]
Le souci semble résolu. Est ce que vous confirmez ?

**Comment by r-jean-pierre** [comment]
Oui, c'est okay les données remontent, j'ai juste eu un petit gap de moins de 24h
Merci pour l'intégration, c'est vraiment bien fait!
