### ISSUE TITLE
Changes in HA 2025.1

### ISSUE THREAD

**Issue by Pulpyyyy** [julcollas/hass-vigicrues#8]
Hello
I saw this warning, in HA logs 
![image](https://github.com/user-attachments/assets/cd6b7a1f-6ec6-4f4b-953a-411b8cc1cf6c)

**Comment by julcollas** [comment]
Hi @Pulpyyyy,

Thanks for reporting. 
It has been changed since
cf https://github.com/julcollas/hass-vigicrues/commit/da99c497f68ae2cf9110181a2bb1ace5a7fbec16

I updated the version. You should receive an updated. Let me know if it's better

**Comment by Pulpyyyy** [comment]
Resolved. Thanks
